_stinger_soft_platform:
    resource: "@StingerSoftPlatformBundle/Resources/config/routing.yml"
    prefix:   /

stinger_soft_gauge_survey:
    resource: "@StingerSoftGaugeSurveyBundle/Resources/config/routing.yml"
    prefix:   /

stinger_soft_gauge_presentation:
    resource: "@StingerSoftGaugePresentationBundle/Resources/config/routing.yml"
    prefix:   /backend/

