StingerSoft\GaugePresentationBundle\Entity\MultipleChoice:
  type:  entity
  fields:
    chartType:
      type: integer
      nullable: true
    allowMultiple:
      type: boolean
      nullable: true
    showResultInPercentage:
      type: boolean
      nullable: true
  oneToMany:
    answers:
      targetEntity: MultipleChoiceAnswer
      cascade: ['persist', 'remove']
      mappedBy: question