StingerSoft\GaugePresentationBundle\Entity\ScaleAnswer:
  type:  entity
  fields:
    answer:
      type: string
      length: 255
      nullable: true
  manyToOne:
    question:
      targetEntity: Scale
      inversedBy: answers