stinger_soft_gauge_presentation_homepage:
    path:     /
    defaults: { _controller: StingerSoftGaugePresentationBundle:Default:index }
    
stinger_soft_gauge_presentation_presentation:
    path:     /presentation/{presentation}
    defaults: { _controller: StingerSoftGaugePresentationBundle:Presentation:index }

    
stinger_soft_gauge_presentation_slide:
    path:     /slide/{slide}
    defaults: { _controller: StingerSoftGaugePresentationBundle:Slide:slide }
    options:
      expose: true
    
    
stinger_soft_gauge_presentation_multiplechoice:
    resource: "@StingerSoftGaugePresentationBundle/Resources/config/routing_multiplechoice.yml"
    prefix:   /multiplechoice/
    
stinger_soft_gauge_presentation_scale:
    resource: "@StingerSoftGaugePresentationBundle/Resources/config/routing_scale.yml"
    prefix:   /scale/
    
stinger_soft_gauge_presentation_wordcloud:
    resource: "@StingerSoftGaugePresentationBundle/Resources/config/routing_wordcloud.yml"
    prefix:   /wordcloud/